### ISSUE TITLE
[BUG] Incorrect Skipped status code processing [JUnit5]

### ISSUE THREAD

**Issue by daliabyeva** [aquality-automation/aquality-tracking#111]
**Describe the bug**
Tests with status code Skipped are imported as Passed

**To Reproduce**
1. Run tests with JUnit5 annotations @Disabled, @DisabledIfSystemProperty or with assumptions not met
2. Import the xml 
3. See test run
4. See that tests are added as Passed

**Expected behavior**
Tests are added as Not Executed

**Desktop (please complete the following information):**
 - JUnit5

**Comment by DmitryBogatko** [comment]
@daliabyeva , the changes are merged. Please, update your tracking instance
