### ISSUE TITLE
[BUG] Incorrect Error status code processing [JUnit5] 

### ISSUE THREAD

**Issue by daliabyeva** [aquality-automation/aquality-tracking#112]
**Describe the bug**
Tests with status code Error are imported as Passed

**To Reproduce**
1. Run tests with JUnit5 resulting in Error status code (Broken test, e.g. failed not on assertion but on inability to complete some step)
2. Import the xml 
3. See test run
4. See that tests are added as Passed

**Expected behavior**
Tests are added as Failed or Broken (same as status Faillure)

**Desktop (please complete the following information):**
 - Junit5

**Comment by DmitryBogatko** [comment]
@daliabyeva , the changes are merged. Please, update your tracking instance
