### ISSUE TITLE
[BUG] Incorrect results merge for NUnit3 tests.

### ISSUE THREAD

**Issue by SeregaFreeman** [aquality-automation/aquality-tracking#123]
**Describe the bug**
Incorrect results merge for NUnit3 tests.

**To Reproduce**
1. Go to 'Import'
2. Select type 'NUnit_v3 (xml)'
3. Add multiple result files to import.
4. Select 'Single test run' option, test name: 'Scenario name'
5. Click 'Import all'

**Expected behavior**
Results are merged correctly: e.g. 58 + 44 tests = 102 total. 

**Actual behavior**
Results are merged incorrectly: 58 + 44 tests = 147 total. Some tests are duplicated. 

**Screenshots**
See screenshots attached.
![tracking_1](https://user-images.githubusercontent.com/3774675/93876492-9b33ef00-fcdf-11ea-840c-ff10dc267690.png)
![tracking_2](https://user-images.githubusercontent.com/3774675/93876494-9bcc8580-fcdf-11ea-8f9d-de4b0d8c7b9b.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version: 1.0.1

**Comment by DmitryBogatko** [comment]
fixed indirectly in v1.2.0
