### ISSUE TITLE
[BUG] Select items on the page

### ISSUE THREAD

**Issue by runetsk** [aquality-automation/aquality-tracking#127]
**Describe the bug**
Click on Select all btn on specific page -> All items from all page are selected
**To Reproduce**
1. Go to 'test runs'
2. Click on 'page 2'
3. Check "SelectAll " label
4. Click on "page 1"
5. Items are selected
**Expected behavior**
1. Go to 'test runs'
2. Click on 'page 2'
3. Check "SelectAll " label
4. Click on "page 1"
5. Items are NOT selected
**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by DmitryBogatko** [comment]
fixed
