### ISSUE TITLE
[BUG] on a dashboard page cannot delete a dashboard

### ISSUE THREAD

**Issue by eugenenekh** [aquality-automation/aquality-tracking#130]
After trying to delete a dashboard:
![image](https://user-images.githubusercontent.com/44803449/103106078-9adf2300-4643-11eb-9dc7-3b46a466c566.png)

v. 1.2.0

**Comment by DmitryBogatko** [comment]
fixed in v1.2.1
https://github.com/aquality-automation/aquality-tracking-ui/releases/tag/v1.2.1
