### ISSUE TITLE
[NF] Add JUnit 5 support 

### ISSUE THREAD

**Issue by dartyuhov** [aquality-automation/aquality-tracking#33]
**Is your feature request related to a problem? Please describe.**
JUnit 5 results import is not supported
![image](https://user-images.githubusercontent.com/30840813/69740344-4882b880-114a-11ea-8fc6-df8b8cd3f05f.png)

**Comment by VladislavKostyukevich** [comment]
@dartyuhov add file example

**Comment by dartyuhov** [comment]
[logintests.xml.zip](https://github.com/aquality-automation/aquality-tracking/files/4019127/logintests.xml.zip)
one test class results

**Comment by VladislavKostyukevich** [comment]
@dartyuhov Try to use TestNG as report type
