### ISSUE TITLE
[NF] add possibility to have a look at all assigned test cases to you

### ISSUE THREAD

**Issue by vasilyevi** [aquality-automation/aquality-tracking#48]
There would be great to have a page which would contain all test executions assigned to you.

Example:
There are 2 test runs. Both contains few failed test cases. Manager assign the test cases to the proper engineer and engineer has a kind of image in the header with a number of assigned test cases to him(like the notifications in different social networks). He clicks on the image and a page with a list of assigned test cases to him opens.

Also would be great to have a email or desktop notification when somebody else(not an engineer) has assign any test case to him

**Comment by VladislavKostyukevich** [comment]
@vasilyevi, Closing this. Covered by Issues.
