### ISSUE TITLE
[NF] Test Run view: Add stability indicator.

### ISSUE THREAD

**Issue by VladislavKostyukevich** [aquality-automation/aquality-tracking#60]
1. Add project setting: Test is stable if was not failed last {n} runs.
2. Add chips to Results table to count app and test issues in stability column
3. Add chips to Tests table to count app and test issues in stability column

**Comment by DmitryBogatko** [comment]
`Add project setting: Test is stable if was not failed last {n} runs.`
 @VladislavKostyukevich , will be the number of runs configurable in the project settings?

**Comment by VladislavKostyukevich** [comment]
Yes, it will.
