### ISSUE TITLE
[BUG] CSV Export (from Test Run or separate Test): filled Assignee field is shown as [object Object]

### ISSUE THREAD

**Issue by caspirt** [aquality-automation/aquality-tracking#88]
**To Reproduce**
1. Go to test run grid and fill Assignee to any user
2. Get CSV as download
3. Open the test statistic page and Get CSV as download

**Expected behavior**
Assignee field is shown as filled 

**Screenshots**
![2020-03-20_0916](https://user-images.githubusercontent.com/14290335/77167489-89516500-6a8c-11ea-8b22-e9789db2a48f.png)

**Comment by VladislavKostyukevich** [comment]
@caspirt Since this column was removed after adding the Issue functionality this bug cannot be reproduced anymore.

If you need this column you can request this feature.
