### ISSUE TITLE
[BUG] Start time doesn't equal to trx start time

### ISSUE THREAD

**Issue by vasilyevi** [aquality-automation/aquality-tracking#90]
**Describe the bug**
After the import of a TRX start time on UI is "Start Time: Apr 07, 2020 10:16:23 PM", but in TRX "start="2020-04-07T19:16:23.7584934-04:00""
**To Reproduce**
1. Import TRX
2. Compare the start time in UI and in TRX

**Expected behavior**
Start time on UM should be the same as in TRX

**Comment by VladislavKostyukevich** [comment]
@vasilyevi this is not a bug the file timezome is -4 and your timezone is +3 that;s why you have 7 hours difference.
