### ISSUE TITLE
[NF] add Failed test cases column(count) to Test Runs table

### ISSUE THREAD

**Issue by vasilyevi** [aquality-automation/aquality-tracking#92]
add Failed Test Cases column(count) to Test Runs table

**Comment by DmitryBogatko** [comment]
@vasilyevi , what is wrong with charts? They should show the number of failed tests:
![image](https://user-images.githubusercontent.com/3273741/79010077-d1cee080-7b69-11ea-8cf0-44e87c237947.png)

**Comment by vasilyevi** [comment]
@DmitryBogatko You have to open each test run to see the count. I need a column on test runs page, to be aware of the count for multiple runs without opening anything

**Comment by VladislavKostyukevich** [comment]
@vasilyevi Why this one does not work for you?
![image](https://user-images.githubusercontent.com/11598034/79317044-def32300-7f0d-11ea-8e4b-b9e2203f319d.png)

**Comment by vasilyevi** [comment]
The percentage doesn't immediately show the exact number. In case if there are a lot of test suits, for me would be better to use exact number of failed test cases. That's just an option to has more flexibility.
